# docker-compose for development configuration

version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - .:/app
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - .:/app
    environment:
      PHP_XDEBUG_ENABLED: 'true'
      XDEBUG_MODE: 'debug'
      XDEBUG_CONFIG: 'client_host=php-cli client_port=9003'

  php-cli:
    build: ./docker/php-cli
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    environment:
      PHP_XDEBUG_ENABLED: 'true'

  postgresql:
    build: ./docker/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    build: ./docker/pgadmin
    restart: always
    ports:
        - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgresql

volumes:
  composer:
  postgresql:
