version: '3.8'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
    volumes:
      - .:/app

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - .:/app

  php-cli:
    build: ./docker/php-cli
    volumes:
      - .:/app
      - composer:/root/.composer/cache

volumes:
  composer:
