### docs https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://nginx/api/login
content-type: application/json

{
    "username": "user@test.com",
    "password": "test"
}

###

